export const places = [
  {
    "id": "chernobyl",
    "name": "CHERNOBYL UNPP",
    "construction_years": "1981 – 1986",
    "planned": "6 REACTORS RBMK-1000",
    "status": "4 BLOCKS COMPLETED & 2 CEASED",
    "description": "Construction of the third stage of the Chernobyl NPP began in 1981, consisting of two RBMK-1000 reactors, each with a capacity of 1000MWe . These units were designed to be identical to the four already in operation, increasing the plant's total output to 6000MWe . The project was critical for meeting the energy demands of the Ukrainian SSR's industrial heartland. By April 1986, construction had reached an advanced stage: Block 5 was approximately 70% complete, with its reactor vessel installed, while Block 6 was in earlier stages of development.\\nThe project was permanently frozen on April 27, 1986, following the catastrophic explosion at the adjacent Reactor 4. While the re-evaluation of the RBMK's critical design flaws was the official reason, the decision was primarily a technical and economic one. The extreme radioactive contamination of the entire site, including the unfinished blocks, made any further construction work physically impossible and financially unthinkable. The cost of decontaminating the advanced structures of Block 5 alone would have been astronomical. The abandoned buildings were simply left to decay, a direct and unavoidable consequence of the disaster.",
    "img_name": "CHERNOBYL_AXO",
    "lat": 51.399,
    "lon": 30.09869,
    "set_id": "pripyat",
    "set_name": "PRIPYAT MONOTOWN, USRR",
    "set_est": 1970,
    "set_planned_pop": "~80,000",
    "set_cur_pop": "~4",
    "set_description": "Founded in 1970, the city of Pripyat was purpose-built as a Soviet \"atomograd\" to serve the Chernobyl NPP. Its population was drawn from across the USSR—a young, highly-educated workforce of specialists attracted by high salaries and an exceptional standard of living. With an average age of just 26, the city was a model of socialist urban planning, boasting modern amenities unavailable in most Soviet cities. It was a place with a clear and prosperous future, planned to grow to nearly 80,000 residents upon the completion of the plant's third stage, which was under construction in 1986. The city was constructed just 3 km from the power plant.\\nPripyat's purpose was catastrophically terminated on April 27, 1986, when its 50,000 residents were evacuated. While many were dispersed, the core workforce was needed to manage the crippled plant, leading to the construction of Slavutych for 25,000 people, the last \"ideal city\" of the USSR, built to house them. Though Slavutych offered a high quality of life and fostered a strong community spirit, it too faced an economic crisis after the final closure of the Chernobyl plant in 2000 leading to the decrease of the population by 20%. Pripyat itself became a ghost town, an icon of nuclear disaster whose silent, decaying structures are a destination for tourism, its identity chained not to a dream of progress, but to its devastating consequences.",
    "set_img": "PRIPYAT MONOTOWN, USRR_AXO"
  },
  {
    "id": "crimea",
    "name": "CRIMEA UNPP",
    "construction_years": "1982 – 1989",
    "planned": "4 REACTORS VVER-1000/320",
    "status": "2 BLOCKS CEASED & 2 CANCELED",
    "description": "The construction of the Crimea NPP began in 1982. The investment aimed at boosting electrical energy for developing cities and advancing industries located in the Crimean Peninsula. Initially, two reactors were planned, with the possibility of expanding the facility by two additional reactors of exactly the same capacity - 1000 MW. If the plant, in its finished form, had been put online, half of the energy produced would have been exported to neighboring regions. Since the construction of the NPP came in times of perestroika, the completion date was constantly moved: from 1980 to 85 and 89. However, in 1987, the investment was put on hold.\\nIn 1989 the construction site was permanently shut down. The financial issues of the Soviet Union was most likely the main reason to abandon the project. In 1985, and in parallel to the development of the UNPP, an experimental Solar Power Plant was built, but due to issues shut down in 1996. In 2005 the plant and its premises were sold to an undisclosed entity for little over 200 000 USD, and in 2009, the very last failed attempt to revive the region was made with an short-lived Wind Power Plant. By 2021 the demolition of the premise started. It is assumed that it will take at least 5 years to remove above-ground structures, and the future of the region is still unknown.",
    "img_name": "CRIMEA_AXO",
    "lat": 45.391711,
    "lon": 35.80331133,
    "set_id": "SHCHOLKINE",
    "set_name": "SHCHOLKINE MONOTOWN, USRR",
    "set_est": 1978,
    "set_planned_pop": "~25,000",
    "set_cur_pop": "~10100",
    "set_description": "In 1978, 4 years prior to the construction of the NPP, the  city of Shcholkine was established on the site of the village of Rybnoye. Named in honor of K. I. Shchelkin, a distinguished Soviet scientist and co-creator of nuclear and thermonuclear bombs. The city, located on the scenic shores of Cape Kazantip, was planned for 25 000 inhabitants from all around USSR, assuming the completion of the NPP. Immediately  after the Chernobyl Disaster in 1986, local communities engaged in a series of protests supported by local media outcry. The residents themselves voted out their own origin myth, hoping to replace it with an alternative of solar or wind power. \\nThe status of the UNPP caused the population of Shcholkine to halve, and those that decided to stay either couldn't sell their real estate or had no other place to go. In other words, Shcholkine was home now. The builders of the UNPP became engaged in fishing and seaside tourism, and an electronic music festival found its home there. Right before the annexation of Crimea by the Russian Federation, the possibility of renaming Schelkino to Kazantip was considered by local authorities, paradoxically, local dwellers were in favor of keeping the original name. The incomplete origin myth, even though voted out originally, is apparently stronger than natural formations that provide jobs for the region.",
    "set_img": "SHCHOLKINE MONOTOWN, USRR_AXO"
  },
  {
    "id": "odessa",
    "name": "ODESSA UNPP",
    "construction_years": "1981 – 1989\t",
    "planned": "2 REACTORS VVER-1000",
    "status": "2 BLOCKS CEASED ",
    "description": "Construction began in 1981 on a nuclear heating and power plant (ATETs) near Teplodar to serve Odessa. The facility was planned to house two VVER-1000/320 reactors, each capable of 1000MWe , and was intended to replace the city's polluting coal and gas boilers. This standardized Soviet design was being deployed across the USSR. By the time the project faced serious opposition, construction was still at a very early stage, with the completion level estimated at only 10-15%, consisting mostly of foundational work and infrastructure for the satellite town of Teplodar.\\nThe project was officially canceled in 1989. While post-Chernobyl public anxiety and official reports on seismic instability were the stated reasons, the decision was also driven by political and economic turmoil. During perestroika, local politicians in the increasingly assertive Ukrainian SSR used the unpopular project to challenge Moscow's authority and build their own political capital. For the crumbling Soviet economy, canceling a project at such an early stage of completion, which already suffered from poor construction quality and financing delays, was an economically pragmatic decision, regardless of the environmental justifications.",
    "img_name": "ODESSA_AXO",
    "lat": 46.4612694,
    "lon": 30.32137222,
    "set_id": "TEPLODAR",
    "set_name": "TEPLODAR MONOTOWN, USRR",
    "set_est": 1981,
    "set_planned_pop": "~20,000",
    "set_cur_pop": "~9,900",
    "set_description": "Founded in 1981 to house workers for the Odessa Nuclear Heating and Power Plant, Teplodar's name literally means “Warmth Giver.” Its first residents were young Komsomol construction brigades from across the Ukrainian and Russian SSRs, drawn by the promise of a modern city designed for 20,000 inhabitants. Construction began on apartment blocks and schools, with the town's identity and future entirely dependent on the success of the nuclear project. The community's very existence was its own origin myth, a testament to a singular, industrial purpose, built only 2 km from the plant site.\\nWhen the plant was canceled in 1989 following public protests, Teplodar became an orphan of the atomic age. The population, which had peaked with construction workers, plummeted and then stagnated at half its planned size. The cancellation triggered a severe economic crisis and a spike in unemployment. While the initial public opinion was strongly against the plant, many residents later expressed regret over the lost economic opportunity. Teplodar remains a living paradox: a community that survived the failure of its founding project, yet is forever defined by the unfulfilled promise embedded in its “Warmth Giver” name.",
    "set_img": "TEPLODAR MONOTOWN, USRR_AXO"
  },
  {
    "id": "kostroma",
    "name": "KOSTROMA UNPP",
    "construction_years": "1980 – 1990\t",
    "planned": "2 REACTORS RBMK-1500",
    "status": "2 BLOCKS CEASED",
    "description": "Construction of the Kostroma NPP began in 1980 near the town of Buy. Initially planned with VVER-1000 reactors, the design was controversially switched to two RBMK-1500 reactors, the most powerful but also most problematic Soviet design, each with a massive output of 1500MWe . This decision created significant technical and logistical challenges, contributing to slow progress. By the time of its cancellation, the project was only at an estimated 15% completion level, consisting primarily of the reactor pit, foundational structures, and the satellite town of Chistye Bory.\\nThe project was abandoned in 1990 amidst a confluence of factors. The immense cost and known technical flaws of the RBMK design, exacerbated by post-Chernobyl safety concerns, made the project economically unviable for the failing Soviet state. The anti-nuclear sentiment was a powerful tool for local politicians in the Kostroma Oblast, who leveraged the issue to assert regional authority against the central government. Furthermore, the region's well-developed natural gas infrastructure provided a convenient and economically preferable alternative, championed by interests within the powerful Soviet fossil fuel industry.",
    "img_name": "KOSTROMA_AXO",
    "lat": 58.37246,
    "lon": 41.605825,
    "set_id": "CHISTYE BORY",
    "set_name": "CHISTYE BORY MONOTOWN, USRR",
    "set_est": 1979,
    "set_planned_pop": "~50,000",
    "set_cur_pop": "~5,200",
    "set_description": "Established in 1979 as the satellite city for the Kostroma NPP, Chistye Bory's name means \"Clean Pine Forests.\" It was designated an \"All-Union Komsomol shock construction project,\" drawing enthusiastic young workers from across the USSR to build a modern city for 50,000 people. In anticipation of the plant's operation, the state invested heavily in high-quality housing, a hospital, and schools. Chistye Bory was a city built in advance, a physical manifestation of Soviet confidence in nuclear energy, waiting for its full population and purpose to arrive just 15 km from the proposed plant.\\nThe 1990 cancellation of the NPP was an existential blow. The population, which at its peak numbered around 10,000 builders, collapsed to under 5,000 as workers left to seek employment elsewhere. Public opinion, which had been fiercely anti-nuclear in the wake of Chernobyl, gradually became divided, with many residents later advocating revival of the project as a remedy to chronic economic stagnation. The once-ironic name “Clean Pine Forests” became literal, as the town remained enveloped in nature—because the industrial giant it was meant to support never came into being. It is now a thinning community, being reclaimed by the pine forest that is steadily encroaching.",
    "set_img": "CHISTYE BORY MONOTOWN, USRR_AXO"
  },
  {
    "id": "tatar",
    "name": "TATAR UNPP",
    "construction_years": "1981 – 1990\t",
    "planned": "4 REACTORS VVER-1000 ",
    "status": "2 BLOCKS CEASED & 2 CANCELED",
    "description": "Construction of the Tatar NPP began in 1981, designed to host four VVER-1000/320 reactors of 1000MWe each. The project was intended to power the massive industrial complexes of the Tatar Autonomous Soviet Socialist Republic. Construction progressed significantly, making it one of the most advanced UNPP projects in the USSR. By 1990, Unit 1 was approximately 70% complete, with the reactor vessel already delivered to the site and major structural work finished. Unit 2 was around 30% complete, while Units 3 and 4 were in the earliest foundational stages.\\nThe project was terminated in April 1990 by a resolution of the Tatar Supreme Soviet. The decision was a major political act of defiance by the Tatar ASSR, which was seeking greater sovereignty from Moscow. While the anti-nuclear movement and geological concerns provided the official justification, the cancellation was also a strategic move by a republic with a powerful, pre-existing oil and gas industry. Halting a major nuclear project from Moscow both asserted political autonomy and protected the dominance of the local fossil fuel economy, leaving a technically advanced but politically doomed site to be cannibalized for other projects.",
    "img_name": "TATAR_AXO",
    "lat": 55.452078,
    "lon": 51.28753611,
    "set_id": "KAMSKIYE POLYANY",
    "set_name": "KAMSKIYE POLYANY MONOTOWN, USSR",
    "set_est": 1981,
    "set_planned_pop": "~50,000",
    "set_cur_pop": "~13,900",
    "set_description": "Established in 1981 as the satellite city for the Tatar NPP, Kamskiye Polyany's name means \"Meadows on the Kama River.\" Planned for 50,000 residents, it was rapidly built to house a diverse workforce of specialists from all corners of the Soviet Union. The influx of highly-paid construction workers and engineers briefly turned the settlement into a bustling frontier town, a symbol of the USSR's continued investment in atomic energy. The city was constructed 8 km away from the Tatar Nuclear Power plant construction site.\\nIn 1990, powerful public protests, fueled by environmental concerns, forced the plant's cancellation. This clear expression of the popular will plunged Kamskiye Polyany into a profound crisis. The population halved as mass unemployment led to a dramatic spike in crime and drug abuse, earning the settlement a notorious reputation in the 1990s. The dream of a futuristic nuclear city was replaced by the reality of a failed monotown. Despite attempts to create industrial parks, the community stands as an example of a future so immense that its failure left a social and economic vacuum yet to be filled.",
    "set_img": "KAMSKIYE POLYANY MONOTOWN, USSR_AXO"
  },
  {
    "id": "voronezh",
    "name": "VORONEZH UNPP",
    "construction_years": "1983 – 1990",
    "planned": "2 REACTORS AST-500",
    "status": "2 BLOCKS CEASED",
    "description": "Construction of the Voronezh Nuclear Heating Plant (VAST) began in 1983. It was a pioneering project featuring two AST-500 reactors, each designed for 500 MW of thermal output for district heating. These reactors were promoted as having \"inherently safe\" features suitable for urban areas. The project reached a very high level of completion before it was stopped: Unit 1 was 90% complete, with all major equipment installed, and Unit 2 was approximately 50% complete. The goal was to replace the city's numerous fossil-fuel boiler houses.\\nThe project was halted in 1990 following intense public protest. However, the cancellation was also a major victory for the established energy interests in the region. The VAST was a direct threat to the numerous coal and gas-fired boiler houses and their fuel suppliers. In the new economic climate of the early 1990s, the prospect of privatizing these existing fossil fuel assets was far more attractive to emerging business and political elites than completing a state-owned nuclear project. The public's genuine safety concerns provided the perfect political cover to abandon the technically advanced plant in favor of the more profitable status quo.",
    "img_name": "VORONEZH_AXO",
    "lat": 51.56148333,
    "lon": 39.14782778,
    "set_id": "SHILOVO",
    "set_name": "SHILOVO MICRORAYON, VORONEZ, USRR",
    "set_est": 1932,
    "set_planned_pop": "~15,000-20,000",
    "set_cur_pop": "~79,000",
    "set_description": "Unlike settlements built from scratch, Shilovo was an existing district on the outskirts of Voronezh slated for expansion to support the VAST. Starting in the 1980s, new microdistricts were built to house thousands of workers. The population was a mix of local Voronezh builders and specialized nuclear engineers brought from across the USSR. This model integrated the industrial project directly into the city's fabric, rather than isolating it in a separate town. The future of the Shilovo district was thus tethered to the successful operation of the plant being built less than 2 km away.\\nThe 1990 cancellation, driven by a local referendum, clearly demonstrated the population's anti-nuclear stance. However, this did not trigger a collapse. Because Shilovo was part of a large metropolis, there was no significant population decline or crime wave; the workforce was simply absorbed into the city's diverse economy. The engine of its specific growth was removed, and the new housing was taken up by the general population. Today, Shilovo is a large residential district whose direct connection to the UNPP is largely forgotten, its origin myth diluted and overwritten by the resilience of a larger urban environment.",
    "set_img": "SHILOVO MICRORAYON, VORONEZ, USRR_AXO"
  },
  {
    "id": "zarnowiec",
    "name": "ZARNOWIEC UNPP",
    "construction_years": "1982 – 1990",
    "planned": " 4 REACTORS VVER-440/213",
    "status": "2 BLOCKS CEASED & 2 CANCELED",
    "description": "Construction of the NPP started in 1981 after a decade of planning. The chosen location was dictated foremostly by the need of providing electricity to the grid in the northern part of Poland. Until this point, energy was imported from the southern region of Silesia, but the losses during the energy transmission were as high as 10% due to the 500 km long distance. The initial investment envisioned two reactor blocks with turbine halls, a training facility, and a hydro plant to support the backup systems for NPP Żarnowiec. The construction site took longer than anticipated, and in 1989, the site was conserved in order to review the project while Poland was transitioning to democracy.  \\nEJ Żarnowiec became a UNPP in 1990, after losing financing and dealing with a public relations crisis. The official reason for abandoning the construction was the lack of need for such a facility. We have to keep in mind that the oil price had dropped by more than 70% since the inception of the project. Nonetheless, the ceased construction generated contractual penalties as high as the budget required to finish the facility. The equipment (including reactors) that had already been delivered to the site was sold to NPPs abroad that were under construction at the time. In modern days, the original location of UNPP Zarnowiec is still considered optimal for another, indeed the first, NPP in the country. ",
    "img_name": "ZARNOWIEC_AXO",
    "lat": 54.742786,
    "lon": 18.09191667,
    "set_id": "ENERGOBUD",
    "set_name": "ENERGOBUD ESTATE, REDA, POLAND",
    "set_est": 1982,
    "set_planned_pop": "~6,000",
    "set_cur_pop": "~9,000",
    "set_description": "The Elektrobud settlement was planned as an integral district of the city of Reda, with over 1200 apartments erected for the construction workers of NPP Zarnowiec. Even though it was the biggest settlement, it represents only 30% of the total number of apartments built for that purpose in 10 different locations. It is estimated that at the peak of the construction efforts, 6000 people were employed in the construction site, only half of the planned workforce required to complete the venture. The builders were earning above-average wages and being provided with unseen at that time in socialist Poland social facilities. The moment the construction paused 5000 full-time positions were terminated. \\nNowadays neither SM Elektrobud nor other settlements link to their incomplete origin myth, even though link is not a secret. The governor of the city of Reda proudly states that the construction of UNPP Żarnowiec helped to attract incomers from the whole country, boosting the development of the region. The city successfully was able to absorb the social infrastructure and unify it, moreover, the district itself is still growing. One may think that a commune that is a part of the bigger urban environment has a possibility to thrive, however, in similar circumstances, the Wohnsiedlung Süd in Stendal was recently demolished, despite its strong link to its own Stendal UNPP. ",
    "set_img": "ENERGOBUD ESTATE, REDA, POLAND_AXO"
  },
  {
    "id": "bashkir",
    "name": "BASHKIR UNPP",
    "construction_years": "1980 – 1990",
    "planned": "4 REACTORS VVER-1000",
    "status": "3 BLOCKS CEASED & 1 CANCELED",
    "description": "Construction of the Bashkir NPP began in 1980 near the city of Agidel. It was a strategic project designed to host four VVER-1000/320 reactors of 1000MWe each, powering the republic's vast petrochemical industry. By the time of its cancellation, the project had reached a significant stage of development, with the first unit estimated to be 20% complete. The main reactor building structure was partially erected, and much of the infrastructure for the site and its satellite city was in place.\\nThe project was canceled in September 1990 by the Bashkir Supreme Soviet. Similar to the Tatar case, this was a potent act of political self-assertion by a republic rich in its own fossil fuel resources. Bashkortostan's powerful oil industry had little to gain from the introduction of a massive nuclear power source controlled by Moscow. Local politicians rode a wave of genuine public concern about geology and river contamination to achieve a dual objective: consolidating their own political power and protecting the dominance of the region's established energy sector, leaving Agidel a monument to this geopolitical struggle.",
    "img_name": "BASHKIR_AXO",
    "lat": 55.8957666,
    "lon": 53.99578,
    "set_id": "AGIDEL",
    "set_name": "AGIDEL MONOTOWN, USSR",
    "set_est": 1980,
    "set_planned_pop": "~40,000",
    "set_cur_pop": "~14,000",
    "set_description": "Founded in 1980, the satellite city of Agidel was meticulously planned for over 30,000 residents to serve the Bashkir NPP. Its population was drawn from industrial centers in the Urals and beyond, attracted by promises of high wages and modern housing. Built in a remote location, it was designed as a self-sufficient ecosystem with high-quality schools and cultural centers. The city's growth and the plant's construction were perfectly synchronized, with the fate of one being completely dependent on the other, located 11 km away.\\nAfter its cancellation in 1990 due to public pressure, Agidel's development halted. The population, which peaked near 20,000, began a slow decline to its current ~14,000. The city faced economic collapse and a demographic crisis as young people left, unable to find work. While public opinion was initially anti-nuclear, it shifted over the decades, with many residents and local authorities lobbying for the project's revival as a cure for economic hardship. The city's incomplete origin myth is a daily reality, visible in the half-empty apartment blocks built for a population that never fully arrived.",
    "set_img": "AGIDEL MONOTOWN, USSR_AXO"
  },
  {
    "id": "stendal",
    "name": "STENDAL UNPP",
    "construction_years": "1982 – 1991",
    "planned": "4 REACTORS VVER-1000/320",
    "status": "2 BLOCKS CEASED & 2 CANCELED",
    "description": "Construction on the Stendal NPP began in 1982 near Arneburg, East Germany. It was a flagship project designed to host four VVER-1000/320 reactors of 1000MWe each, making it the largest planned NPP in Germany. Despite chronic delays, the project reached a very advanced stage. By 1990, Unit 1 was 85% complete (though not fueled), Unit 2 was 50% complete, and foundational work had begun on Units 3 and 4. The plant was intended to reduce the GDR's reliance on polluting lignite coal.\\nStendal was canceled in March 1991 following German reunification. The official reason was the prohibitive cost of upgrading the plant to Western safety standards. However, powerful economic factors were also at play. The influential West German coal industry, along with labor unions, lobbied to protect the massive lignite mining industry in the former East, which employed tens of thousands. Abandoning the nearly complete nuclear plant and continuing to subsidize lignite was a politically and economically expedient choice for the newly unified government, ensuring social stability in the region at the cost of the nuclear project.",
    "img_name": "STENDAL_AXO",
    "lat": 52.72421944,
    "lon": 12.0192055556,
    "set_id": "HOUSING ESTATE SOUTH",
    "set_name": "ESTATE SOUTH, STENDAL, GDR",
    "set_est": "1980s",
    "set_planned_pop": "~8,000",
    "set_cur_pop": "SETTLEMENT DEMOLISHED",
    "set_description": "The Wohnsiedlung Süd in Stendal was a massive complex of Plattenbau blocks erected in the 1980s. It was a purpose-built district for the international workforce of the Stendal UNPP, including specialists from the USSR, Poland, and Hungary. As a typical socialist project, it provided thousands of standardized apartments for the builders of the GDR's nuclear future. Its identity was inextricably linked to the nearby construction site, a concrete symbol of the state's ambition located approximately 12 km away.\\nAfter German reunification and the 1991 cancellation of the NPP, the estate lost its purpose. The departure of workers created massive housing surplus, and the population plummeted. The district fell into decline, suffering from high unemployment, social decay, and becoming a symbol of post-reunification economic hardship in East Germany. The population's opinion on the closure was one of resignation to the new political and economic reality. In the 2000s, large parts of the estate were demolished as part of a state-funded urban renewal program, a pragmatic solution to erase a redundant piece of a failed industrial dream.",
    "set_img": "ESTATE SOUTH, STENDAL, GDR_AXO"
  },
  {
    "id": "kharkov",
    "name": "KHARKOV UNPP",
    "construction_years": "1985 – 1990",
    "planned": "4 REACTORS VVER-1000",
    "status": "4 BLOCKS CANCELED",
    "description": "The decision to build the Kharkiv Nuclear Heating and Power Plant (KhATETs) was made in 1982. The design featured two VVER-1000/320 reactors of 1000MWe each, intended to provide heat and power to the metropolis of Kharkiv. The project was a direct threat to the network of existing coal-fired heating plants in the city. By the time of its cancellation, the plant was at a very minimal completion level of less than 10%, with only site preparation, some road infrastructure, and foundational pits completed.\\nThe project was formally canceled in 1990. The escalating economic crisis of the late Soviet period meant that funding for the technically-demanding project had all but disappeared. Public opposition after Chernobyl provided a convenient justification for local political figures in the Ukrainian SSR to challenge the authority of the central government by halting a major, Moscow-directed project. For the deeply troubled Soviet economy, abandoning a project at such a low level of completion was a simple financial calculation, effectively cutting losses on an investment that was no longer politically or economically feasible.",
    "img_name": "KHARKOV_AXO",
    "lat": 49.6879,
    "lon": 36.0680999,
    "set_id": "ATOMNYE BORKI",
    "set_name": "ATOMNYE BORKI MONOTOWN, USRR",
    "set_est": "mid 1980s",
    "set_planned_pop": "~35,000",
    "set_cur_pop": "SETTLEMENT NEVER COMPLETED",
    "set_description": "The settlement for the Kharkiv KhATETs, colloquially known as \"Atomnye Borki,\" never materialized beyond the planning stage. The plan called for a modern district for 35,000 residents drawn from across the USSR to build and operate the plant. Initial site preparations began in the mid-1980s, marking the first steps toward creating a new nuclear community. However, this was not a remote project; it was an extension of the village of Birky on the outskirts of Ukraine's second-largest city, Kharkiv, and was planned just 5 km from the plant site.\\nAbandoned after the Chernobyl disaster and officially canceled in 1990, \"Atomnye Borki\" never became a settlement and thus never had a population to fluctuate or a society to collapse. The powerful public opinion in Kharkiv against the plant, amplified by the 1986 catastrophe, ensured its early demise. Unlike functional but purposeless towns like Teplodar, the Kharkiv settlement is a ghost of a ghost town—a place that was never born. Its origin myth is a footnote in planning documents, the site itself reclaimed by nature, leaving almost no physical trace.",
    "set_img": "ATOMNYE BORKI MONOTOWN, USRR_AXO"
  },
  {
    "id": "gorky",
    "name": "GORKY UNPP",
    "construction_years": "1982 – 1993",
    "planned": "2 REACTORS AST-500",
    "status": "2 BLOCKS CEASED",
    "description": "Construction of the Gorky Nuclear Heating Plant (GAST) began in 1982 within the city of Gorky. The experimental design featured two AST-500 reactors, each providing 500 MW of thermal output for district heating. The project was remarkably advanced before its cancellation. By 1993, Unit 1 was 95% complete and was being prepared for testing, while Unit 2 was approximately 60% complete. The plant was designed to be a clean heat source, replacing the city's many fossil-fuel boilers.\\nThe GAST was canceled following a 1993 city-wide referendum. While driven by genuine public fear, the referendum was also influenced by the turbulent politics of post-Soviet Russia. Local politicians used the anti-nuclear platform to build their careers in the new democratic landscape. Furthermore, the cancellation directly benefited the newly privatized natural gas industry and the operators of the old boiler houses, who would have been put out of business by the GAST. The public vote, therefore, served both the political ambitions of local elites and the economic interests of the established fossil fuel sector.",
    "img_name": "GORKY_AXO",
    "lat": 56.21752,
    "lon": 44.0624889,
    "set_id": "SELECTION",
    "set_name": "SELECTION STANTION VILLAGE",
    "set_est": 1930,
    "set_planned_pop": "UNKNOWN",
    "set_cur_pop": "~4,000",
    "set_description": "The settlement for the Gorky GAST was not a new city but an existing suburban community. The plan was to build the GAST directly adjacent to residential districts, whose residents became the project's designated neighbors, not its builders. The workforce itself was composed of local Gorky residents and specialists from across the USSR, who were housed not in a new town but in newly built apartment blocks within existing city districts like Shcherbinki. This integration of the plant, located less than 3 km away, and its workers into the city's fabric was a key feature of the project.\\nThis unique position transformed the settlement into the epicenter of the anti-GAST movement. The population's opinion was unequivocally against the plant, a sentiment powerful enough to drive a successful 1993 referendum that canceled the project. The community did not suffer from the plant's closure; on the contrary, it viewed the cancellation as a victory. The settlement's relationship with its UNPP is one of rejection. It fulfilled a new purpose by defending its own existence from what it perceived as a threat, turning the incomplete origin myth of the GAST into the complete origin myth of a citizen-led environmental triumph.",
    "set_img": "SELECTION STANTION VILLAGE_AXO"
  },
  {
    "id": "juragua",
    "name": "JURAGUA UNPP",
    "construction_years": "1983 – 1992",
    "planned": "4 REACTORS VVER-440/318",
    "status": "2 BLOCKS CEASED & 2 CANCELLED",
    "description": "The project started as a joint-venture with the Soviet Union as a part of a bigger scheme which aimed at providing alternative sources of energy with the use of 12 reactors in 3 different locations in Cuba. Juragua NPP was envisioned to cover 15% of national energy needs, decreasing the dependence on foreign oil imports. Two reactor blocks were the very first nuclear facility designed by the Soviet Union for export. Along with construction efforts, whole new scientific and technical infrastructure was established in Cuba, including an international program to study in USSR. The venture was supervised by a Cuban nuclear scientist, the oldest son of Castro —  Fidel Castro Diaz-Balart.\\nJuragua became a UNPP in 1992, four years before the already iterated opening date. Despite the efforts of the president Castro, no external investors were able to financially support the project, mostly due to the successful efforts of the USA to block investment deemed “too close” to Florida. Up till this point, the project had burned through 1.1 bln USD and popular misinformation suggested that a country like Cuba couldn't sustain an investment of such a magnitude. The so-called \"investment of the century\" had failed to facilitate the scientific and technological development of the country. In 2018, Fidel Castro Diaz-Balart took his own life after struggling with depression. ",
    "img_name": "JURAGUA_AXO",
    "lat": 22.09999444,
    "lon": -80.5132805556,
    "set_id": "NUCLEAR CITY",
    "set_name": "NUCLEAR CITY MONOTOWN, CUBA",
    "set_est": 1980,
    "set_planned_pop": "~20,000",
    "set_cur_pop": "~5,500",
    "set_description": "Located less than 5 km from planned confinement buildings, Nuclear City was established in 1980, 3 years before the start of the construction of the NPP. Initially designed with 4200 dwellings in mind, it was equipped with schools, clinics, and all the marvels of a socialist top-down planned city. It was proudly compared to the city of Pripyat, which at the time had only 6 more years of life. This socialist heterotopia in the making was providing housing for construction workers, scientists, and engineers, including Soviet consultants from Atomenergoexport. In the meantime, new Cuban nuclear personnel was getting trained in the USSR, planning to settle here once they complete their education.\\nCurrently, the settlement is half-empty. In the remote location, the half-finished city connected by half-finished roads has only been thinning since 1989. Employment can be found 30 km away in distant Cienfuegos, where a port and industrial complex is located. Once considered a perfect location away from the capital, it has become a periphery chained to an unfinished concrete cathedral of science. The pursuit of a new complete future for the region rendered 1300 Cuban nuclear scientists unable to find employment; they thus dispersed. The recent collaboration with Venezuela revived the region’s oil refineries, making the pursuit for scientific and technological development of the region redundant. ",
    "set_img": "NUCLEAR CITY MONOTOWN, CUBA_AXO"
  },
  {
    "id": "belene",
    "name": "BELENE UNPP",
    "construction_years": "1987 – 1990; 2005 - 2012",
    "planned": "2 REACTORS VVER-1000/466B",
    "status": "2 BLOCKS CEASED",
    "description": "The Belene NPP project has a protracted history. The first phase began in 1987, centered on building four VVER-1000/320 reactors of 1000MWe each. This phase reached a completion level of approximately 40% for the first unit's main structures before being halted. The second attempt in 2005 involved two modern VVER-1000/466B (AES-92) reactors. This project was also canceled, but only after the two complete reactor vessels and other long-lead equipment had been manufactured and delivered.\\nThe project was first halted in 1990 due to post-communist economic collapse. Its revival and second cancellation in 2012 were the result of complex geopolitical and economic factors. The project was caught between Western pressure to limit Russian energy influence and Russian pressure to complete the plant. Internally, the project was a political battleground, with shifting governments and competing domestic oligarchs using the multi-billion-euro contracts as a source of political leverage. Powerful interests in the existing energy sector, particularly those connected to coal plants and energy trading, also benefited from the persistent delays and eventual cancellation of a major new competitor.",
    "img_name": "BELENE_AXO",
    "lat": 43.638739,
    "lon": 25.216469,
    "set_id": "DIMUM",
    "set_name": "DIMUM ESTATE, BELENE, HUNGARY",
    "set_est": "1980s",
    "set_planned_pop": "~9,000",
    "set_cur_pop": "SETTLEMENT NEVER COMPLETED",
    "set_description": "The community tied to the Belene UNPP is the ancient town of Belene (Dimum). The project did not create a new satellite city but reshaped an old one. Starting in the 1980s, construction brought an influx of workers from across the CMEA bloc, including the USSR and Hungary, nearly doubling the town's population. This created a boomtown atmosphere, with investment pouring into a new residential district and a sense of a modern, industrial future replacing the quiet, agricultural past. Belene's identity became inextricably linked to the promise of the nuclear energy facility being built 7 km away.\\nThe cancellations in 1990 and 2012 subjected Belene to devastating boom-and-bust cycles. Each halt triggered a mass exodus of workers, a population collapse, and a spike in unemployment. Public opinion became deeply polarized between those who saw the plant as the only path to prosperity and those who feared its geopolitical and environmental risks. This perpetual frustration has held the community in a state of suspended animation for decades, unable to move forward while the spectre of the UNPP—with its vast, empty site and two unused reactors—looms over its future.",
    "set_img": "DIMUM ESTATE, BELENE, HUNGARY_AXO"
  }
];
